### ISSUE TITLE
Create "npm run images" functionality

### ISSUE THREAD

**Issue by stephensavoia** [stephensavoia/swcsg#13]
**I think Sharp is the node.js library to use for this** 

Create functionality that allows a user to type "npm run images" to create resized images. When the user types "npm run images" in the terminal, the following should happen:

1. Check the folder "src/assets/img/comic" for .jpg files that have not yet been processed (i.e. title is like 001.jpg).
2. For each unprocessed .jpg, rename the current file "{old name}-2048.jpg", then create the 1600px wide version of the file called "{old name}-1600.jpg" and an 800px wide version of the file called "{old name}-800.jpg".

| "src/assets/img/comic" before           | "src/assets/img/comic" after                                     |
|-------------------|-------------------------------------------|
| 001.jpg <br> 002.jpg <br> 003.jpg | 001-2024.jpg <br> 001-1600.jpg <br> 001-800.jpg <br> 002-2024.jpg <br> 002-1600.jpg <br> 002-800.jpg <br> 003-2024.jpg <br> 003-1600.jpg <br> 003-800.jpg |

**Comment by broneks** [comment]
Make the script idempotent.
